// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.hoteach.proto;

public final class StudentProto {
  private StudentProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hoteach_protobuf_MyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hoteach_protobuf_MyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hoteach_protobuf_MyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hoteach_protobuf_MyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hoteach_protobuf_StudentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hoteach_protobuf_StudentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hoteach_protobuf_StudentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hoteach_protobuf_StudentResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hoteach_protobuf_StudentResponseList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hoteach_protobuf_StudentResponseList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rStudent.proto\022\024com.hoteach.protobuf\"\035\n" +
      "\tMyRequest\022\020\n\010username\030\001 \001(\t\"\036\n\nMyRespon" +
      "se\022\020\n\010realname\030\002 \001(\t\"\035\n\016StudentRequest\022\013" +
      "\n\003age\030\001 \001(\005\":\n\017StudentResponse\022\014\n\004name\030\001" +
      " \001(\t\022\013\n\003age\030\002 \001(\005\022\014\n\004city\030\003 \001(\t\"U\n\023Stude" +
      "ntResponseList\022>\n\017studentResponse\030\001 \003(\0132" +
      "%.com.hoteach.protobuf.StudentResponse2\304" +
      "\002\n\016StudentService\022\\\n\025GetRealNameByUserna" +
      "me\022\037.com.hoteach.protobuf.MyRequest\032 .co" +
      "m.hoteach.protobuf.MyResponse\"\000\022c\n\020GetSt",
      "udentsByAge\022$.com.hoteach.protobuf.Stude" +
      "ntRequest\032%.com.hoteach.protobuf.Student" +
      "Response\"\0000\001\022o\n\030GetStudentsWrapperByAges" +
      "\022$.com.hoteach.protobuf.StudentRequest\032)" +
      ".com.hoteach.protobuf.StudentResponseLis" +
      "t\"\000(\001B#\n\021com.hoteach.protoB\014StudentProto" +
      "P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_hoteach_protobuf_MyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_hoteach_protobuf_MyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hoteach_protobuf_MyRequest_descriptor,
        new String[] { "Username", });
    internal_static_com_hoteach_protobuf_MyResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_hoteach_protobuf_MyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hoteach_protobuf_MyResponse_descriptor,
        new String[] { "Realname", });
    internal_static_com_hoteach_protobuf_StudentRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_hoteach_protobuf_StudentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hoteach_protobuf_StudentRequest_descriptor,
        new String[] { "Age", });
    internal_static_com_hoteach_protobuf_StudentResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_hoteach_protobuf_StudentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hoteach_protobuf_StudentResponse_descriptor,
        new String[] { "Name", "Age", "City", });
    internal_static_com_hoteach_protobuf_StudentResponseList_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_hoteach_protobuf_StudentResponseList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hoteach_protobuf_StudentResponseList_descriptor,
        new String[] { "StudentResponse", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
